name: Deploy to Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: 'source ~/.nvm/nvm.sh; cd ~/server/; ./update.sh; ./deploy.sh cultivar; exit'
          host: bonjovi.socioambiental.org
          username: '-J diego@186.225.123.194:29382 terrakrya'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
